### ISSUE TITLE
/haiku options are not correct

### ISSUE THREAD

**Issue by MercWorks** [ibanner56/OtherDave#206]
Options show "save" etc, rather than "-save"

![image](https://user-images.githubusercontent.com/1631598/201728909-9e1c012e-8fae-4d6b-9539-61791b153ee1.png)
![image](https://user-images.githubusercontent.com/1631598/201728982-6ba27eb8-87ce-4764-8146-ffdf51e6a16c.png)

**Comment by ibanner56** [comment]
Yes, that's how command parameters work, unfortunately. You need to tack on keywords (which is what you needed to do before, it just defaulted to the immediate previous haiku if you didn't provide any). I could take in the same longer command string that !haiku used to consume, but then we're back to the same confusing usage that app commands were meant to address.

The only way to preserve a similar behavior would be to use sub-commands, like `/mimic`, but it doesn't support top-level AND sub-commands on the same keyword. This is why it's `/mimic user` now instead of just `/mimic` when you want to mimic yourself.
